[project]
authors = ["haivubui <buivuhai1105@gmail.com>"]
channels = ["conda-forge", "Pypi"]
name = "MDROT"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cudatoolkit = ">=11.8.0,<12"
cupy = ">=13.4.0,<14"
numba = ">=0.61.0,<0.62"
tensorflow = ">=2.18.0,<3"
python = ">=3.12.9,<3.13"
pytorch = ">=2.6.0,<3"
scipy = ">=1.15.2,<2"
keras = ">=3.8.0,<4"
jax = ">=0.5.2,<0.6"
pip = ">=25.1.1,<26"
pandas = ">=2.2.3,<3"

[pypi-dependencies]
argparse = ">=1.4.0, <2"
numpy = "*"
scipy = "*"
matplotlib = ">=3.10.3, <4"
torch = "*"
torchvision = ">=0.21.0, <0.22"
torchaudio = ">=2.6.0, <3"


